### Verbo GET – listar
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token:abcBolinhasToken
x-key:abcBolinhasKey


### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
x-token:abcBolinhasToken
x-key:abcBolinhasKey
content-type: application/json

{
        "nome" : "Abc da Silva",
        "matricula" : "12345",
        "cpf" : "01923874656",
        "telefone" : "49988234567",
        "grupo" : 1,
        "senha" : "bolinhas"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
x-token:abcBolinhasToken
x-key:abcBolinhasKey
content-type: application/json

{
        "nome" : "Bolinhas dos Testes",
        "matricula" : "54321",
        "cpf" : "12345678909",
        "telefone" : "49898989",
        "grupo" : 2,
        "senha" : "abc"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
x-token:abcBolinhasToken
x-key:abcBolinhasKey